# Configurações gerais do inventário de warps
inventory:
  size: 27 # deve ser múltiplo de 9 entre 9 e 54
  title: "§6Warps" # título do inventário

  # Slots de cada warp no inventário (key é o nome da warp em minúsculo)
  slots:
    exemplo: 11
    spawn: 13
    loja: 15

  # Itens para cada warp com nome e lore personalizáveis
  items:
    exemplo:
      name: "&eWarp Exemplo"
      lore:
        - "&7Clique para teleportar"
    spawn:
      name: "&aWarp Spawn"
      lore:
        - "&7Teleporte para o spawn principal"
    loja:
      name: "&bWarp Loja"
      lore:
        - "&7Acesse a loja do servidor"